name: Render README

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [ "main" ]
    paths: [ ".github/actions", "awesome.yaml" ]
  pull_request:
    branches: [ "main" ]
    paths: [ ".github/actions", "awesome.yaml" ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * FRI"

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Render README
        uses: ./.github/actions/awesome
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}

      - name: Commit & push (only on push/schedule/dispatch)
        if: github.event_name != 'pull_request'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "📝 Update README" || echo "No changes"
          git push
